alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - localhost:9093
global:
  evaluation_interval: 5m
  scrape_interval: 5m
  scrape_timeout: 1m
rule_files:
- price.rules
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- job_name: airfare_exporter
  static_configs:
  - targets:
    - localhost:8000
- job_name: alertmanager
  static_configs:
  - targets:
    - localhost:9093
